name: Deploy MERN Stack to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_ENV: production
  AZURE_WEBAPP_NAME: melvins-simon
  CLIENT_DIR: client
  SERVER_DIR: server

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: |
            ${{ env.CLIENT_DIR }}/package-lock.json
            ${{ env.SERVER_DIR }}/package-lock.json

      # Clean installation for client
      - name: Clean Install Client Dependencies
        working-directory: ${{ env.CLIENT_DIR }}
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm install @vitejs/plugin-react vite @types/react @types/react-dom --save-dev

      # Build Client
      - name: Build React App
        working-directory: ${{ env.CLIENT_DIR }}
        run: npm run build

      # Install Server Dependencies
      - name: Install Server Dependencies
        working-directory: ${{ env.SERVER_DIR }}
        run: npm ci --production

      # Prepare Deployment Structure
      - name: Create Deployment Package
        run: |
          mkdir -p deployment
          # Copy server files
          cp -r ${{ env.SERVER_DIR }}/* deployment/
          # Create the exact ../client/dist structure
          mkdir -p client/dist
          cp -r ${{ env.CLIENT_DIR }}/dist/* client/dist/
          # Keep root files
          cp ${{ env.SERVER_DIR }}/package.json deployment/
          cp ${{ env.SERVER_DIR }}/package-lock.json deployment/

      # Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./deployment
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A136AE9F94A44295BD9C97B14723879E }}
