name: Build and Deploy

on:
  push:
    branches: [main]

env:
  NODE_VERSION: "22.x"
  AZURE_WEBAPP_NAME: "melvins-simon"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build client
        run: |
          cd client
          npm install
          npm run build

      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r server/* deployment/
          cp -r client/dist deployment/client-dist
          cp package.json deployment/
          cp package-lock.json deployment/
          cp server.js deployment/
          cd deployment && zip -r ../deployment.zip .

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EA54DDA088BE4E0D936DB00FF8DD69B8 }}
          package: deployment.zip
